- block:
  # root

  - name: 'Install disk-monitoring packages'
    package:
      name:
        - hddtemp
        - procps-ng
        - smartmontools
      state: latest

  - name: 'Enable SMART systemd service'
    ansible.builtin.systemd:
      name: 'smartd'
      state: 'started'
      enabled: 'yes'

  - name: 'Enable SMART monitoring on all devices'
    shell: |
      lsblk | grep disk | awk '{print $1}' | xargs -I {} smartctl --smart=on /dev/{}
    ignore_errors: true
    changed_when: false

  - name: "Install disk-monitoring scripts"
    template:
      src: "{{ item }}"
      dest: "/usr/bin/{{ item | basename | regex_replace('\\.j2$', '') }}"
      owner: "root"
      group: "root"
      mode: 0755
    with_items:
      - "disk-status.j2"

  become: yes
