---
- block:
  # root

  - name: 'Install Docker'
    package:
      name:
        - docker
        - docker-compose
        - python
        - python-pip
        - python-docker
        - python-yaml
      state: latest

  - name: 'Install Docker Python Packet for root'
    pip:
      name: "{{ item }}"
    with_items:
      - "docker-compose"

  - name: 'Add users to docker group'
    user:
      name: '{{ username }}'
      groups: 'docker'
      append: 'yes'

  - name: 'Enable docker systemd service'
    ansible.builtin.systemd:
      name: 'docker'
      state: 'started'
      enabled: 'yes'

  - name: 'Create default docker-bridge network'
    docker_network:
      name: docker-bridge

  - name: 'Create default isolated network'
    docker_network:
      name: isolated
      internal: yes

  become: yes


- block:
  # user

  - name: 'Install Docker Python Packet for user'
    pip:
      name: "{{ item }}"
    with_items:
      - "docker"
      - "docker-compose"
