---

- name: "Install base package group"
  include_role:
    name: archlinux/install
  vars:
    packages: "{{ base.packages }}"
    pip_packages: "{{ base.pip_packages }}"
    services: "{{ base.services }}"


- block:
  # root

  - name: "Updatedb"
    shell:
      cmd: updatedb

  become: yes


- block:
  # user

  - name: "Initialize git lfs"
    shell:
      cmd: git lfs install >/dev/null 2>&1
    failed_when: false
