---

- name: "Install de-kde package group"
  include_role:
    name: system/install
  vars:
    packages: "{{ de_kde.packages }}"


- block:
  # root

  - name: "Set keymap to {{ keymap }}"
    shell:
      cmd: "localectl set-keymap {{ keymap }}"

  - name: "Set x11 keymap to {{ x11_keymap }}"
    shell:
      cmd: "localectl set-x11-keymap {{ x11_keymap }}"

  - name: "Set locale to {{ lang }}"
    shell:
      cmd: "localectl set-locale LANG={{ lang }}"

  - name: "Disable ballo"
    shell:
      cmd: "baloctl disable"

  become: yes
