---
- hosts: archlinux
  roles:

    - role: archlinux/precondition
    - role: package-groups/xorg
    - role: package-groups/wm-base
    - role: package-groups/wm-xorg
    - role: package-groups/wm-xmonad

