---
- block:
  # root

  - name: 'System update'
    pacman:
      update_cache: yes
      upgrade: yes

  - name: 'Install base packages'
    package:
      name: "{{ base_packages }}"
      state: latest

  - name: 'Install pip packages for root'
    pip:
      name: "{{ item }}"
    with_items: "{{ base_pip_packages }}"

  - name: "Updatedb"
    shell:
      cmd: updatedb

  - name: 'Enable base systemd services'
    ansible.builtin.systemd:
      name: '{{ item }}'
      state: 'started'
      enabled: 'yes'
    with_items: "{{ base_services }}"

  - name: "Create the aur_builder user"
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: "Allow the aur_builder user to run sudo pacman without a password"
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  become: yes

- block:
  # user

  - name: 'Install pip packages for user'
    pip:
      name: "{{ item }}"
    with_items: "{{ base_pip_packages }}"

  - name: "Initialize git lfs"
    shell:
      cmd: git lfs install >/dev/null 2>&1
    failed_when: false
