---
- block:
  # root

  - name: "Get user home stat"
    stat:
      path: "/home/{{ username }}"
    register: user_home

  - name: "Throw error if user home not exists"
    fail:
      msg: "/home/{{ username }} does not exists"
    when: not user_home.stat.exists

  - name: 'System update #1'
    pacman:
      name: 'archlinux-keyring'
      state: latest
      update_cache: yes

  - name: 'System update #2'
    pacman:
      update_cache: yes
      upgrade: yes

  - name: 'Install base packages'
    package:
      name:
        - openssl
        - python-pip
        - python-setuptools
        - rustup
      state: latest

  - name: "Allow user to run sudo pacman without a password"
    lineinfile:
      path: /etc/sudoers.d/12-user-install
      line: '{{ username }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: 'rustup install stable for {{ username }} user'
    shell: |
      rustup install stable
    become_user: "{{ username }}"

  - name: 'rustup set stable as default for {{ username }} user'
    shell: |
      rustup default stable
    become_user: "{{ username }}"

  become: yes

