---

- name: "Install login-lightdm package group"
  include_role:
    name: system/install
  vars:
    packages: "{{ login_lightdm.packages }}"

- name: 'Enable lightdm systemd service'
  systemd:
    name: 'lighdm'
    enabled: 'yes'
  become: yes
