---

- name: "Install vmware-guest package group"
  include_role:
    name: system/install
  vars:
    packages: "{{ vmware_guest.packages }}"
    service: "{{ vmware_guest.service }}"

  become: yes
